services:
  app:
    build: .
    container_name: sso-app
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ENV=docker
      - DB_HOST=shared-postgres  # Подключается к общей БД
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=url_shortener
      - REDIS_ADDR=shared-redis:6379  # Подключается к общему Redis
      - DB_SSLMODE=disable
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - REDIS_MAX_RETRIES=3
      - REDIS_DIAL_TIMEOUT=10s
      - REDIS_TIMEOUT=5s
      - KAFKA_ADDRESS=shared-kafka:9092  # Подключается к общей Kafka
      - KAFKA_TOPIC=topic
      - KAFKA_NETWORK=tcp
      - KAFKA_PARTITIONS=1
      - KAFKA_REPLICATIONS=1
      - KAFKA_GROUP_ID=test-group
      - GRPC_PORT=8081
      - GRPC_TIMEOUT=10h
      - TOKEN_TTL=1h
      - CONFIG_PATH=/app/config/docker.yaml
    networks:
      - shared-network

networks:
  shared-network:
    external: true
    name: shared-network